# Generated by Django 4.2.6 on 2023-12-16 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postalcode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[1-9]\\d{5}$', 'Enter a valid 6-digit postal code.')]),
        ),
    ]
