# Generated by Django 4.2.6 on 2023-10-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='otp',
        ),
    ]
