# Generated by Django 4.2.6 on 2023-11-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_category_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
