# Generated by Django 4.2.6 on 2023-11-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0010_remove_orderitem_cancel_order_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='main_customuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='main_customuser_user_permissions', to='auth.permission'),
        ),
    ]
