# Generated by Django 4.2.6 on 2023-11-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, choices=[(7, '7'), (8, '8'), (9, '9')], default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
