# Generated by Django 4.2.6 on 2023-11-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
    ]
