# Generated by Django 4.2.6 on 2023-11-30 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
