# Generated by Django 4.2.6 on 2023-11-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_wallet_user_delete_transaction_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(default='cod', max_length=225),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
