# Generated by Django 4.2.6 on 2023-11-30 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_customer_wallet_order_payment_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_cancel',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='returned',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('transaction_balance', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
