# Generated by Django 4.2.6 on 2023-12-01 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
