# Generated by Django 4.2.6 on 2023-12-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_order_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='selected_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_address_for_customer', to='main.address'),
        ),
    ]
