# Generated by Django 4.2.6 on 2023-12-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_order_payment_method_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default='nothing', on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
