# Generated by Django 4.2.6 on 2023-12-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
